### ISSUE TITLE
Admin cadastra filial

### ISSUE THREAD

**Issue by TatianaRo** [TreinaDev/esperto-fit-filiais#1]
Cada filial deve conter um nome, um código alfanumérico único, endereço, horário de funcionamento e uma galeria de fotos. O horário de funcionamento deve contemplar o horário de abertura e fechamento de cada dia da semana e de feriados. Não é preciso distinguir os horários para cada feriado especificamente.

Subsidiary
{
-name
-token
-address
-images
-opening_hours
}

- [x] Admin acessa Home page e seleciona gerenciar filiais 

- [x] Seleciona criar nova filial

- [x] Preenche os dados e envia

-name
-token
-address
-images
-opening_hours (rever)
-CNPJ

- [x] Todos os atributos são obrigatórios

- [x] Nome da filial deve ser única

- [x] Token da filial deve conter 6 caracteres alfanuméricos

- [x] CNPJ deve ser válido

**Comment by joaorsalmeida** [comment]
Minha sugestão: quebrar essa issue em duas. Uma para cadastrar a filial e outra para gerenciar o horario de funcionamento da filial. Me parece uma lógica que pode dar trabalho pra fazer junto com o cadastro puro e simples da filial.
