### ISSUE TITLE
Validação de filial

### ISSUE THREAD

**Issue by TatianaRo** [TreinaDev/esperto-fit-filiais#12]
-name
-token
-address
-images
-opening_hours (rever)
-CNPJ

- [ ] Todos os atributos são obrigatórios

- [ ]  Nome da filial deve ser única

- [ ] Token da filial deve conter 6 caracteres alfanuméricos

- [ ] CNPJ deve ser válido

- [ ] WIP: Cadastrar horários de abertura

**Comment by joaorsalmeida** [comment]
Pessoal, esse tipo de issue não faz mais sentido. Esse tipo de detalhe (validação) deve ser tratado junto com o cadastro ;)
