### ISSUE TITLE
Admin cadastra funcionário

### ISSUE THREAD

**Issue by TatianaRo** [TreinaDev/esperto-fit-filiais#3]
Eu, administrador, cadastro um funcionário e o associo a uma filial, além de criar um email para que ele possa logar no sistema.

User{
id
email
senha
role  (admin or employee),
}

profile (
subsidiary , 
 full_name , 
CPF,
address,
user_id
)

**Comment by flpfar** [comment]
## Critério técnicos
- [ ] Criar specs de feature
- [ ] Gerar migration
- [ ] Executar a migration
- [ ] Criar specs pro model
- [ ] Gerar o model
- [ ] Criar as rotas
 - [ ] Profile new, create, show, index
- [ ] Criar os controllers
- [ ] Criar as views

## Critérios funcionais
- [ ] Admin deve ter uma tela para cadastrar perfis
- [ ] Admin deve ter uma tela para visualizar perfis cadastrados
- [ ] Admin deve vincular perfil à uma filial
- [ ] Senha é gerada de acordo o CPF
